# Generated by Django 3.2.23 on 2024-01-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_category_en_category_category_ja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_vi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
