# Generated by Django 3.2.23 on 2024-01-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_category_vi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_vi',
        ),
    ]
