# Generated by Django 4.2.7 on 2023-11-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_news_description_en_news_description_ja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ja',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
