# Generated by Django 3.2.23 on 2024-01-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_news_photo_alter_news_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_vi',
            field=models.TextField(null=True),
        ),
    ]
