# Generated by Django 4.2.6 on 2023-10-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_stupid',
        ),
    ]
