# Generated by Django 3.2.23 on 2023-11-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_complete',
            field=models.BooleanField(default=False),
        ),
    ]
